// =====================================================================
// identity.js — derive (and persist) the bridge's 64-bit node ID.
//
// The bridge is a server-class peer in the Axona network — what the
// integration plan calls a "highway node."  Its identity is stable
// across restarts so other peers see it as a reliable, well-known
// transit hub.
//
// 64-bit node ID layout matches axona-peer (NH-1 production format):
//
//     ┌──────────────────────────┬────────────────────────────────────┐
//     │  S2 cell prefix          │  random bits                       │
//     │  8 bits  (GEO_BITS=8)    │  56 bits                           │
//     └──────────────────────────┴────────────────────────────────────┘
//
// The prefix is derived from `BRIDGE_LAT` / `BRIDGE_LNG` env vars
// (defaults to 38.0/-77.0, US-East Virginia where the production
// bridge runs).  Operators set them to the bridge's real location;
// the S2 cell makes the bridge appear in the geographically-correct
// neighborhood of the routing table.
//
// Persistence: `bridge-identity.json` in the working directory (or
// `BRIDGE_IDENTITY_PATH` override).  Read once at startup; written
// once on first generation.  Subsequent restarts pick up the same
// bottom-56-bits, so the bridge's nodeId is stable.
//
// Future: replace the bottom-56-bits with a hash of an Ed25519 key
// generated by the operator (private key stays on the server,
// public key embedded as identity).  For now: random bits.
// =====================================================================

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname } from 'node:path';
import { mkdirSync } from 'node:fs';

import {
  geoCellId,
  randomU64,
} from '@axona/protocol';

const GEO_BITS = 8;

const DEFAULT_LAT = 38.0;     // US-East Virginia
const DEFAULT_LNG = -77.0;

function pathFromEnv() {
  return process.env.BRIDGE_IDENTITY_PATH ?? 'bridge-identity.json';
}

function regionFromEnv() {
  const lat = parseFloat(process.env.BRIDGE_LAT ?? DEFAULT_LAT);
  const lng = parseFloat(process.env.BRIDGE_LNG ?? DEFAULT_LNG);
  const label = process.env.BRIDGE_REGION_LABEL ?? `bridge (${lat.toFixed(2)}, ${lng.toFixed(2)})`;
  return { lat, lng, label, id: 'bridge' };
}

/**
 * @typedef {Object} BridgeIdentity
 * @property {bigint}  id
 * @property {number}  geoBits
 * @property {Object}  region    { lat, lng, label, id }
 * @property {number}  createdAt
 */

/**
 * Load the persisted identity from disk, or derive a fresh one and
 * persist it.  Synchronous (we want it ready before the server
 * starts listening).
 *
 * @returns {BridgeIdentity}
 */
export function loadOrDeriveIdentity() {
  const path = pathFromEnv();

  if (existsSync(path)) {
    try {
      const raw = readFileSync(path, 'utf8');
      const stored = JSON.parse(raw);
      return {
        id:        BigInt('0x' + stored.id),
        geoBits:   stored.geoBits ?? GEO_BITS,
        region:    stored.region  ?? regionFromEnv(),
        createdAt: stored.createdAt ?? 0,
      };
    } catch (err) {
      // Corrupt or unparseable — fall through to fresh generation.
      console.error(`bridge-identity: failed to read ${path}: ${err.message}; generating fresh`);
    }
  }

  const region = regionFromEnv();
  const prefix = geoCellId(region.lat, region.lng, GEO_BITS);
  const shift  = 64n - BigInt(GEO_BITS);
  const bottom = randomU64() & ((1n << shift) - 1n);
  const id     = (BigInt(prefix) << shift) | bottom;

  const identity = {
    id,
    geoBits:   GEO_BITS,
    region,
    createdAt: Date.now(),
  };

  // Ensure parent dir exists, then write.
  try {
    const parent = dirname(path);
    if (parent && parent !== '.' && !existsSync(parent)) {
      mkdirSync(parent, { recursive: true });
    }
    writeFileSync(path, JSON.stringify({
      id:        identity.id.toString(16).padStart(16, '0'),
      geoBits:   identity.geoBits,
      region:    identity.region,
      createdAt: identity.createdAt,
    }, null, 2));
  } catch (err) {
    console.error(`bridge-identity: failed to persist to ${path}: ${err.message}`);
  }
  return identity;
}

/** Format a nodeId as a 16-char hex string (Axona wire convention). */
export function idToHex(id) { return id.toString(16).padStart(16, '0'); }
